// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX77gHB7MZOLxlIKQwS_sjNR-haIKt3bI',
    appId: '1:934798291532:web:dea57df4208047faa77ae9',
    messagingSenderId: '934798291532',
    projectId: 'authentication-2c4f3',
    authDomain: 'authentication-2c4f3.firebaseapp.com',
    databaseURL: 'https://authentication-2c4f3-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-2c4f3.appspot.com',
    measurementId: 'G-LCB57FF9XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGPxsg_IfVv7P2_5P-wzrvUi5DfZ2jBw',
    appId: '1:934798291532:android:290a7892ea63c4e0a77ae9',
    messagingSenderId: '934798291532',
    projectId: 'authentication-2c4f3',
    databaseURL: 'https://authentication-2c4f3-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-2c4f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCipfwN81U8bVG4dDBUZOp80eyIFG4KZY',
    appId: '1:934798291532:ios:f415d0d985c256a8a77ae9',
    messagingSenderId: '934798291532',
    projectId: 'authentication-2c4f3',
    databaseURL: 'https://authentication-2c4f3-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-2c4f3.appspot.com',
    iosClientId: '934798291532-l51cn2qqmisa7letr72dtjev3k6u7fv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCipfwN81U8bVG4dDBUZOp80eyIFG4KZY',
    appId: '1:934798291532:ios:176317f6eaa772c3a77ae9',
    messagingSenderId: '934798291532',
    projectId: 'authentication-2c4f3',
    databaseURL: 'https://authentication-2c4f3-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-2c4f3.appspot.com',
    iosClientId: '934798291532-7qarc1jqo8enlbl6alqlbcn1vpeua685.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
